name: fabdashboard
description: A new Flutter project.
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
 
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  firebase_database: ^9.1.6
  firebase_auth: ^3.11.0
  firebase_storage: ^10.3.10
  ionicons: ^0.2.1
  get: ^4.6.5
  jiffy: ^5.0.0
  file_picker: ^5.2.0+1
  side_navigation: ^1.0.2
  flutter_form_builder: ^7.6.0
  flutter_filereader: ^3.0.0
  cloud_firestore: ^3.5.0
  multi_image_layout: ^0.0.5
  responsive_grid_list: ^1.3.0
  expandable_text: ^2.3.0
  image_picker: ^0.8.5+3
  uuid: ^3.0.6
    
  
 
  web_browser: ^0.5.0
  rotated_corner_decoration: ^2.0.0
  firebase: ^9.0.3
  shimmer: ^2.0.0
  firebase_messaging: ^13.1.0
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
   
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0
 
flutter:
 
   uses-material-design: true

   assets:

    - assets/images/
    - .env
   fonts:
     - family: Poppins
       fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
   
          weight: 700